steps:
- name: node
  entrypoint: npm
  args: ['install']

- name: node
  entrypoint: npm
  args: ['run', 'test']

- name: node
  entrypoint: npm
  args: ['run', 'build']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'stitch']

timeout: 1600s